Document: selenium-server
Title: Debian selenium-server Manual
Author: <insert document author here>
Abstract: This manual describes what selenium-server is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/selenium-server/selenium-server.sgml.gz

Format: postscript
Files: /usr/share/doc/selenium-server/selenium-server.ps.gz

Format: text
Files: /usr/share/doc/selenium-server/selenium-server.text.gz

Format: HTML
Index: /usr/share/doc/selenium-server/html/index.html
Files: /usr/share/doc/selenium-server/html/*.html
